#define       ESC  0x011b
#define        UP  0x4800
#define      DOWN  0x5000
#define      LEFT  0x4b00
#define     RIGHT  0x4d00
#define      PGUP  0x4900
#define    PGDOWN  0x5100
#define      HOME  0x4700
#define       END  0x4f00
#define       INS  0x5200
#define       DEL  0x5300
#define	    Enter  0x1C0D
#define        F1  0x3b00
#define        F2  0x3c00
#define        F3  0x3d00
#define        F4  0x3e00
#define        F5  0x3f00
#define        F6  0x4000
#define        F7  0x4100
#define        F8  0x4200
#define        F9  0x4300
#define       F10  0x4400
#define  ShiftF10  0x5d00
#define   ShiftF9  0x5c00
#define   ShiftF8  0x5b00
#define   ShiftF7  0x5a00
#define   ShiftF6  0x5900
#define   ShiftF5  0x5800
#define   ShiftF4  0x5700
#define   ShiftF3  0x5600
#define   ShiftF2  0x5500
#define   ShiftF1  0x5400
#define     AltF1  0x6800
#define     AltF2  0x6900
#define     AltF3  0x6a00
#define     AltF4  0x6b00
#define     AltF5  0x6c00
#define     AltF6  0x6d00
#define     AltF7  0x6e00
#define     AltF8  0x6f00
#define     AltF9  0x7000
#define    AltF10  0x7100

#define    CtrlF1  0x5e00
#define    CtrlF2  0x5f00
#define    CtrlF3  0x6000
#define    CtrlF4  0x6100
#define    CtrlF5  0x6200
#define    CtrlF6  0x6300
#define    CtrlF7  0x6400
#define    CtrlF8  0x6500
#define    CtrlF9  0x6600
#define   CtrlF10  0x6700

#define        BS  0x0e08
#define       TAB  0x0f09
#define	 SHIFTTAB  0x0f00
#define        CR  0x1c0d
#define     SPACE  0x3920
#define  GreyPlus  0x4e2b
#define  GreyMinus 0x4a2d
#define  CtrlHOME  0x7700
#define  CtrlEND   0x7500
#define  CtrlPGUP  0x7601
#define  CtrlPGDOWN 0x7600
#define  CtrlLeft  0x7300
#define  CtrlRight 0x7400
#define  CtrlEnter 0x1c0a
#define  CtrlDEL   0x0093

#define	AltQ	0x1000
#define	AltW	0x1100
#define	AltE	0x1200
#define	AltR	0x1300
#define	AltT	0x1400
#define	AltY	0x1500
#define	AltU	0x1600
#define	AltI	0x1700
#define	AltO	0x1800
#define	AltP	0x1900

#define	AltA	0x1e00
#define	AltS	0x1f00
#define	AltD	0x2000
#define	AltF	0x2100
#define	AltG	0x2200
#define	AltH	0x2300
#define	AltJ	0x2400
#define	AltK	0x2500
#define	AltL	0x2600

#define	AltZ	0x2c00
#define	AltX	0x2d00
#define	AltC	0x2e00
#define	AltV	0x2f00
#define	AltB	0x3000
#define	AltN	0x3100
#define	AltM	0x3200

#define  CtrlA     0x1e01
#define  CtrlB     0x3002
#define  CtrlC     0x2e03
#define  CtrlD     0x2004
#define  CtrlE     0x1205
#define  CtrlF     0x2106
#define  CtrlG     0x2207
#define  CtrlH     0x2308
#define  CtrlI     0x1709
#define  CtrlJ     0x240a
#define  CtrlK     0x250b
#define  CtrlL     0x260c
#define  CtrlM     0x320d
#define  CtrlN     0x310e
#define  CtrlO     0x180f
#define  CtrlP     0x1910
#define  CtrlQ     0x1011
#define  CtrlR     0x1312
#define  CtrlS     0x1f13
#define  CtrlT     0x1414
#define  CtrlU     0x1615
#define  CtrlV     0x2f16
#define  CtrlW     0x1117
#define  CtrlX     0x2d18
#define  CtrlY     0x1519
#define  CtrlZ     0x2c1a
 
// new keys added by new int09 ISR
#define	CtrlIns	   0x5204
#define	CtrlUp	   0x4804
#define	CtrlDown   0x5004





